menu:
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/leoliiiiii'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/zhihan-li-126429192/'}

contacts:
- {name: 'Zhihan Li', phone: '(408) 427-1658', email: 'zhihanli@andrew.cmu.edu', image: 'assets/img/contact.jpg'}
